//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyProj.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Auditorium
    {
        public string AuditoriumID { get; set; }
        public string Auditorium_type { get; set; }
        public Nullable<int> AUDITORIUM_CAPACITY { get; set; }
    
        public virtual Auditorium_type Auditorium_type1 { get; set; }
    }
}
