//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyProj.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student
    {
        public int StudentID { get; set; }
        public Nullable<int> GroupID { get; set; }
        public string Name { get; set; }
        public Nullable<System.DateTime> Bday { get; set; }
        public string Info { get; set; }
    
        public virtual Groups Groups { get; set; }
    }
}
