//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyProj.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Teacher
    {
        public string TEACHERid { get; set; }
        public string TEACHER_NAME { get; set; }
        public string PULPIT { get; set; }
        public string SUBJECT { get; set; }
    
        public virtual Pulpit Pulpit1 { get; set; }
    }
}
